# Generated by Django 4.1 on 2022-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Puzzle',
                'verbose_name_plural': 'Puzzles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('draft', models.BooleanField(default=True, verbose_name='Draft')),
                ('username', models.CharField(max_length=50, verbose_name='User name')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'User Puzzle',
                'verbose_name_plural': 'Users Puzzles',
                'ordering': ['id'],
            },
        ),
    ]
