# Generated by Django 4.1 on 2022-08-29 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpuzzle',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userpuzzle',
            name='username',
        ),
        migrations.AddField(
            model_name='userpuzzle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
