# Generated by Django 4.1 on 2022-09-02 09:06

from django.db import migrations, models
import puzzles.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='format +380xxxxxxxxx', max_length=13, null=True, validators=[puzzles.models.validate_phone], verbose_name='Phone'),
        ),
    ]
