# Generated by Django 4.1 on 2022-09-05 11:09

from django.db import migrations, models
import puzzles.models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_alter_customuser_options_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='format +380xxxxxxxxx', max_length=13, null=True, validators=[puzzles.models.validate_phone], verbose_name='Phone'),
        ),
    ]
